### ISSUE TITLE
Move repository to laminar organisation

### ISSUE THREAD

**Issue by der-On** [X-Plane/XPlane2Blender#320]
As I'm no more maintaining this repository but laminar does, it would be better to move it to a "laminar research" organisation at github.

This would also include:
- changing links to this repo in the forum thread and webpages
- adding a hint to this repo description where to find the new repo
- adding a hint to the README where to find the new repo

**Comment by tngreene** [comment]
Thank you for thinking about this, I've been thinking about the same.

I think a Transfer over a fork would be best. As per [Github documentation](https://help.github.com/articles/about-repository-transfers/), a transfer automatically redirects links, resources, and etc as opposed to a fork which does none of those things.

It should defintely be a transfer to an organization, as opposed to accidentally transferring it to @bsupnik  or myself.

I'd like to do this before the next beta, and certainly before rc1. less links, less visibility, less bookmarks, less hassle.

**Comment by tngreene** [comment]
So, its been almost a year, and we've now shipped v3.5.0-rc.1. I think its time we re-open this conversation and do the account-accept-confirm-password-change-permission-set shell game.

The reason I mention this again is that I was trying to solve an issue with gitbooks, and is says that the integration needs to be updated.

I'm pretty sure it is free, but if it isn't (or if it is) which only you seem to be able to do. While not a big shop stopper, I just think it is time. What do you think @bsupnik , @der-On

**Comment by tngreene** [comment]
# Moving XPlane2Blender
- [Github Help On Transferring vs Forks](https://help.github.com/articles/about-repository-transfers/).
- [Github Help on Transferring From a Personal Account to An Organization](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/)

1. Briefly add @der-On to our @X-Plane organization, ensuring he has repo creation privileges (Member is enough).
2. @der-On follows instructions under "Transferring a repository to another user account or to an organization" putting "XPlane2Blender" for name, "X-Plane" for Organization name
3. @bsupnik, with his Owner privileges, accepts the transfer
4. We change our git remote names (best practices), test we can pull and push and change code.
5. Remove @der-On from @X-Plane
6. @der-On doesn't fork or create a new repo called XPlane2Blender and every link will redirect to @X-Plane!

# Moving XPlane2Blender-docs
See instructions above, but for `https://github.com/der-On/XPlane2Blender-docs/`.

1. @der-On goes to the [XPlane2Blender-doc settings page](https://legacy.gitbook.com/book/der-on/xplane2blender-docs/settings), and transfers the book to "ted_x_plane"
2. I update the Github Integration and all is well.

Sound good to everyone? What day/time should we do this?

**Comment by der-On** [comment]
@tngreene As I wont be available until the 29th October we should schedule this after the 29th October. For me it should be possible to do the move between 9:30 GMT+1 and 21:00 GMT+1

**Comment by tngreene** [comment]
@bsupnik sound good to you?

**Comment by der-On** [comment]
@bsupnik @tngreene As this was quite for some time I would like to bump it up, so we can make finally the move?

**Comment by tngreene** [comment]
How about Wednesday or Thursday? It'll give me enough time to re-scrape all the issues, save all the docs and wikis and stuff just in case. We'll get on Skype and do it all.

**Comment by der-On** [comment]
@tngreene Sounds good. So it would be April 17th. I'm available from 9:00 GMT+2 until 16:00 GMT+2

**Comment by der-On** [comment]
@tngreene I've now transfered everything as you described above.
Travis needs some fiddling now, but should work after that.

**Comment by tngreene** [comment]
This is fantastic thank you.
Can you also transfer the docs repo? How do we get Travis done?

**Comment by der-On** [comment]
@tngreene Done!

**Comment by tngreene** [comment]
Status of manual: I tried to upgrade my account because it kept bothering me and saying GitHub integration wouldn't work without it and Gitbooks messed up and lost everything and I can't get them to e-mail me back. All the links to the manual are dead, and appear to be dead forever since non-paying members have no support and I'll be you anything they'll say "Sorry, its a one way transfer!". So, screw them and their terrible service I hate and have hated for a long time!

*Don't worry I made a complete backup because I didn't trust them!*

New plan:

- [ ] Just use XPlane2Blender-docs (or maybe even this project if I figure out how it works) and GitHub's Pages feature to make a doc website of our own here. No outside service, no integration, no unusual permissions. No bad editors, no fake version control.
- [ ] Update links to the various forum posts, developer docs, etc. I've been careful not to make too many
- [ ] Make a post telling people the manual moved.

**Comment by arb65912** [comment]
Independent documentation would be a big plus for users in my opinion. The one where you can attach pictures etc. Keeping fingers crossed Ted.

**Comment by tngreene** [comment]
@bsupnik Changing the header "Scenery & Cockpit import & export scripts for Blender and the X-Plane Flight Simulator" to

"X-Plane aircraft and scenery .obj exporter addon for Blender" (Or something similar you like) can, stupidly, only be done by an Owner.

I'd appreciate changing it since
1. We don't have an importer
2. We don't need a reference to `http://xplane2blender.anzui.de/`

**Comment by tngreene** [comment]
> 
> 
> Independent documentation would be a big plus for users in my opinion. The one where you can attach pictures etc. Keeping fingers crossed Ted.

What is the difference between
1. https://x-plane.gitbooks.io/xplane2blender-docs/content/v3-5/howtomakeastuff.md
2. https://x-plane.github.io/xplane2blender/v3-5/howtomakeastuff.md
3. https://x-plane.readthedocs.io/en/v3-5/howtomakestuff.md

I'm not sure what you mean by "Independent". I want to avoid extra accounts and complex integrations with github.

As long as we're forced to make a new fresh start (unless Gitbook support tells me they've magically fixed everything), why sign up for another account somewhere and set up another integration which will one day break?

Why add another middle man?

**Comment by arb65912** [comment]
I can not open any of the links above, 

I might misunderstand the explanations here. What I meant was not to open another account but have documentation with ability to insert images.
The last time I looked there was no that ability at all or lack of pictures was intentional.

I am sorry if I made a confusion.
My only concern is that users have a nice documentation in a safe place preferably with some illustrations.

Question: are you going to post in org forums about where we will be getting new documentation after all is sorted out after transfer etc.?

**Comment by tngreene** [comment]
Yes, this is just a bit of a confusing mess sorry.

Users will, of course, be getting the best I can give. Images, articles, bullet point lists, and even italics when they're in the budget (I kid).

I'll let the community know in all the places I usually post release notes. Dev blog and forums.

And for a historical note: This is a very annoying thing to have to deal with. I really hope Gitbook support gets back to me so I can put this off for a longer time.

**Comment by arb65912** [comment]
I do not want to take **_too_** much time here but thank you Ted!

Hope things will be simple for you (still can not imagine how are you keeping up will all the exporter fixes/requests etc.)

**Comment by tngreene** [comment]
Yay bothering support worked! The manual is back online just how it was!

**Comment by arb65912** [comment]
Happy to hear!!!
Ted, could you please explain about the move repository to laminar organization?
Is there going to be a different location for GitHub etc?
Or all stays the same for a user like me?
Thanks!

**Comment by tngreene** [comment]
Everything is exactly the same. In fact all the links to issues, commits, wiki pages, releases, etc all get automatically re-directed (unless Ondrej makes a fork - please don't do that.)

Ondrej got tired of having to deal with requests relating to managing this, and there is a certain programmer instinct of separating concerns.

I was, in fact, not planning on telling anyone about the move because there is no reason to. Only this manual fiasco deserved mention but now it appears to be fixed.

As proof, you found yourself here without even realizing there was a move, right?

**Comment by arb65912** [comment]
Great! Yes, I found myself here but I noticed that  the beginning is different now :-) **X-Plane**/XPlane2Blender
Thank you very much!

**Comment by tngreene** [comment]
Status:
- [x] GitHub is transferred
- [x] XPlane2Blender-docs *on GitHub* is transferred
- [x] XPlane2Blender-docs *on GitBooks Legacy* is trasferred to *ted_x_plane*, a gitbooks account I made out of frustration when attempting to sign in with @tngreene wasn't working, now making this more complicated
- [x] ted_x_plane was upgraded to the new App version
- [x] ted_x_plane is the owner of the organization XPlane2Blender-docs, which has a "space" (aka book) called XPlane2Blender-docs leaving us with a very very long url for our manual pages.
- [ ] Give ted_x_plane's Organization *XPlane2Blender-docs*'s GitHub integration access to X-Plane/XPlane2Blender-docs, via @tngreene doing this with my OAuth
- [ ] I forceably push all of my backup copy from the legacy version to X-Plane/XPlane2Blender-docs
- [ ] I, logged with ted_x_plane, use @tngreene's OAuth and XPlane2Blender-doc's Organization GitHub integration to import from the GitHub repository X-Plane/XPlane2Blender

By this point we will have
- The X-Plane GitHub Organization XPlane2Blender-docs repo completely up to date
- ted_x_plane's Organization XPlane2Blender-docs "Space" called XPlane2Blender-docs integrated (through @tngreene) to X-Plane/XPlane2Blender-docs
- The GitBook organization's "Space" imported content will completely match the legacy content.
- [ ] I hit "Complete Migration" and all links from the legacy to the modern will match
- [ ] We get some breathing room to plan out the move to GitHub Pages and eventually lop this %$$#@ tumor off of us, putting a disclaimer where the new thing is and forgetting about GitBooks forever until they shutdown for being aweful.

**Comment by tngreene** [comment]
Travis was moved May 24th, 2019 to [https://travis-ci.org/X-Plane/XPlane2Blender/builds/](). That means the only thing left is all in my court - update the link forwarding and keep updating the manual. Thanks so much to @der-On for all his development time on this project, for transitioning this so gracefully, and generally being a great guy.

I'm making a new bug simply to track my progress in the link forwarding. Done!

And just as a reminder to @der-On , please do not fork XPlane2Blender or it'll all break. Yay!

**Comment by tngreene** [comment]
A heads up to @der-On, I removed the reference to `https://xplane2blender.anzui.de/` from the project settings.
