### ISSUE TITLE
Custom Light Texture Coordinates don't match UV values in blender?

### ISSUE THREAD

**Issue by lehthanis** [X-Plane/XPlane2Blender#395]
This may be a documentation issue or is more than likely a lack of understanding on my behalf, but I figured I'd raise it here since this seems to be the only place I can ever get answers about 3d modeling. (Thanks Ted!! If you'd rather me ask these questions elsewhere, let me know)

I'm trying to create a custom light in my cockpit obj and I'm missing the answers to so many questions.  The primary of which, is that the UV coordinates provided in the UV editor don't seem to correspond to the S1,T1,S2,T2 values...And I'm not sure what values I should be using?  Is 0,0 bottom left of my UV texture space?

If you want to also maybe answer these questions in this space that'd be cool too:
-Can a custom light be part of a cockpit obj?
-Can a custom light be inside of transparent geometry (like a light inside a gear handle)
--Does that gear handle geometry need to be in a separate glass blended obj?
-Does the billboard graphic need to be in the lit texture, or the albedo texture or both?
-and my above question, where do we derive the texture coordinates in blender?

**Comment by tngreene** [comment]
Custom Lights are not deprecated (because they provide a unique feature we don't plan on removing from X-Plane), but also not recommended. They are indeed under documented (but not entirely undocumented!)

Read these
- [Developer Blog Post On Custom Lights](https://developer.x-plane.com/?article=custom-lights)
- [XPlane2Blender manual](https://der-on.gitbooks.io/xplane2blender-docs/content/v3.4/settings_reference/34_lamp_settings.html)

All of LIGHT_CUSTOM's data comes directly from that box, not the UV editor. Its a "manual" process through and through that won't really be getting better, the autocorrect algorithm doesn't even run on it when it could. There isn't any validation either.

Unless these get a LOT more popular this won't change much. Dan Klaue uses these a lot to make hi s airplanes more distinct from the rest. He may or may not want to help you get started using them, because, after all, the more people who use this feature means it has to get more support.

**Comment by tngreene** [comment]
Did you ever figure out what you needed with Custom Lights?

**Comment by tngreene** [comment]
If you still need help, feel free to comment or get in touch.
