### ISSUE TITLE
280: Don't export Objects that are not in the Exportable Root's scene

### ISSUE THREAD

**Issue by tkyler** [X-Plane/XPlane2Blender#411]
Using root mode export in "Scene A".   Auto-detect textures OFF, manual paths/names for albedo and normal.  Exporting gives me error of "ERROR: Circle.1667: No Material found"....except that Circle.1667 is a mesh, unparented to anything and in a completely differing Blender scene, i.e. 'Scene B'.

**Comment by tkyler** [comment]
FWIW, Additional Note.  When I open a new blender file and 'append' the scene I am trying to export, it exports out fine.

**Comment by tngreene** [comment]
The issue turned out to be that since the exporter only looks at parent-child relationships it could recuse down the parent-child tree into Datablocks that were in other scenes, including them or finding errors there. Very unexpected, since the Outliner doesn't show those relationships.

The fix breaks the workflow of anyone who is depending on this kind of behavior, which I hope is no one.

**Comment by tngreene** [comment]
Re-opening because current_scene_exclusive_collection.test is not working properly. scene got changed from error to warning because several unit tests which feature multiple scenes would get errors - between each test case the scene wasn't switching so comparing to the "current scene" would be wrong.

4 immediate ideas to this problem:
1. Emit a warning for out of scene (current strategy to just keep things moving)
2. Have every test case specify what scene it should be tested with if there are multiple scenes (tedious)
3. Never (or almost never and see choice 2) test the exporter with a .blend file using multiple scenes (not a good idea, because many bugs have been discovered accompanied by "oh no, we didn't account for multiple scenes!)
4.  Change the predicate in code from `error/skip if child_obj not in context.scene.objects` to `error/skip if child_obj not in all_scene_objects` where `all_scene_objects` is some kind of dictionary or collection of all the objects in the scene the exportable object or exportable collection is in. This would be calculated once and accessed in the recurse function. If the artist had an exportable object in multiple scenes, the exporter would be able to deal with it by just choosing the current scene and we just promise to never write a unit test that is that complicated (since we can't garuntee the current scene)
5. We change some unit tests to run each test case in order so we can organize the test cases per scene and switch once. (This is making my skin crawl.)

**Choice 4 is a very complicated solution for a very simple problem:** The addon as normally run can easily guarantee a current scene or a sequence of scenes but a unit test cannot.

I propose this rule for unit tests for now: **Never make a unit test with multiple scenes, except when needed for testing the updater and specific needs. If you are testing a .blend file with multiple scenes, explicitly change the current scene so the predicate: `error/skip if child_obj not in context.scene.objects`**

The means, also, a new unit test testing that exporting with multiple scenes is possible. The key line is 

`bpy.context.window.scene = bpy.data.scenes['something']`

**Comment by tngreene** [comment]
The other question: If the exporter detects an object out of scene as a child, should it error or warn, then skip recursing into it?

Case for error:
Object in other scene is semantically wrong and also not obvious why the object would be skipped. After all, another scene means in a way different place in the Outliner with no clue as to where. It probably happened by mistake, and might take a long time to figure out what happened. Why allow it at all?

Plus, people never read warnings.

Case for warning:
Artists might like to temporarily stash unused work in another scene but not lose the parentage. Who am I to say they're wrong. Also, in 2.79, this was not an error or a warning, it was silently skipped.

I think we'll go with warning and hope people read it.

**Comment by arb65912** [comment]
Since we have all different opinions, here is mine.

Definitely option 1. to make exporter working and make things simple.

There is no really a necessity for using objects being in different scenes for a normal work in my opinion.

I would like to know the flow for exporting cockpitobj and manipulators as well as other aircraft objects as they are in Plane Maker.

There is part of documentation on the Root Object export but I think a simple good example would go a long way .

Thank you for all the hard work Ted!

**Comment by tngreene** [comment]
@arb65912 Wow, thanks for the quick feedback!

**Comment by arb65912** [comment]
ha, ha. You are welcome. Many things here you discuss and describe are above my head unfortunately but I read all you say... :-)

**Comment by tngreene** [comment]
Closing because we have the feature done, the conflict is in the unit tester. The issue I posed in 645db56 can be made into its own design choice.
