### ISSUE TITLE
Weird Shading

### ISSUE THREAD

**Issue by Zulfiqarib** [X-Plane/XPlane2Blender#434]
Hi , 

 Not an expert in graphics but i have managed around a 100 buildings for my hometown - Mumbai a few months back but then i stopped modeling due to work.  

 Since a few days i am back at it again and definitely haven't forgotten anything much. So i made a new building with a helipad , i wanted to really get into PBR stuff but when i had tried that a few months back it was very weird and the same shading was being seen on those buildings, hence those models are now without any normal maps.

Would appreciate if someone could point a tutorials for using normals in XP , there is one that i tried to follow but it didn't work.

 So the new building which i made and exported using XP2BL 3.5.1b1 , has that same gray shade , i am only using a plain white and a cream texture for the building and helipad. 
 
 So i had a discussion about it @developer XP. 
 
 Not sure if this would a modelling issue or not.

Hmm can't upload files here ?

Rgds

Zulfikar

**Comment by tngreene** [comment]
From my testing, it turned out to be flipped normals and potentially an incorrect texture path (for my computer, which doesn't have the same folders as yours :) )

The key was visualizing them in the 3D Viewer, and I saw the problem right away.

For whatever reason you got it to work for you, I'm very glad!

**Comment by Zulfiqarib** [comment]
Yeah Ted and thanks for looking into it even though it was a user error.
