### ISSUE TITLE
autodetect textures

### ISSUE THREAD

**Issue by tkyler** [X-Plane/XPlane2Blender#472]
Hey Ted....What is the 'governing criteria' for the script to autodetect textures and write the path/name into the OBJ file?.  The tooltip says, "based on materials", which is a bit ambiguous.  I have a material on a mesh, it has a single image texture assigned to it for the albedo, but no image path info gets written to the OBJ on export.  This implies to me that there's something more specific required, some name format perhaps?....and I'm curious what that is.

If I manually select the texture, all is fine...but that kind of defeats the purpose of autodetection.

**Comment by tngreene** [comment]
Related to #449, #399, and #429, and a couple others (man we've been talking about this a lot lately!).

You have to tell the exporter at some point what to fill in TEXTURE and TEXTURE_LIT and etc with. In 2.49 this was done with the UV/Image Editor. In 2.79 we offer two options: Simply uncheck `Auto-detect Textures` and fill in the paths yourself per OBJ or...

1. Make sure you are using Blender Render (which has been removed in 2.80)
2. Make sure every material in an OBJ has an Image Texture block for TEXTURE, TEXTURE_LIT, TEXTURE_NML, etc
3. Make sure each of those Image Texture block's file path is the same or you'll get an error
4. Make sure the correct "Influence" checkbox is checked per texture slot correctly to say that the Image Texture represents NML instead of the albedo. (Only explained in the manual)
5. What do you get out of all this? Blender Render shows your Texture in the 3D View, just like the UV Textures used to be able to do and you'll get a few more warning messages which I don't know how helpful they are.

The more I thought about it, the less I like it, and it won't even be supported in 2.80 by Blender or myself. My biggest advice is to use the first option.
