### ISSUE TITLE
Exportable Collection should ignore children outside of collection during collection, not a warning or error

### ISSUE THREAD

**Issue by dpospisil** [X-Plane/XPlane2Blender#498]
I have been testing 450-use-of-collections today as this feature is essential to our workflow.

I understand that this feature is not finished yet but I have noticed that if it is exporting a collection it also exports all children of an object of that collection regardless if they are also part of that collection or not. Is this intended behavior?

I guess this is not as this is not in par with what "Export by Layers" used to do in 2.7.

I can provide test file in the case this description does not make sense.

**Comment by tngreene** [comment]
Tell me if the new title doesn't make sense.

# About using code directly from .git
Love the enthusiasm! But, I highly recommend asking me for a build before using code directly from git. It provides several benefits, such as including code that is not yet online and an easier time telling what .blend file has been experienced what code.

Sometimes I make commits in small chunks or that I know are totally broken but I just want to save my progress. People get surprised by this and wonder and start debugging the addon. Sometimes a bad commit will totally destrory some work!

Ask for the latest, and you'll get something better than the latest.

**Using code directly from git means you are totally responsible for whatever happens to your .blend files.**

Anyway....

# Should Exportable Collections Collect Children Outside The Collection
You have brought up a very good design question!

Suppose we have
```
ExportableCollection
|_Cube
  |_ChildCube1
  |_ChildCube2 (not in ExportableCollection)
```

Which ChildCubes should be included during recursive collection?

1. If we say both it matches how Blender thinks of Collections, that child relationships remain the same no matter what the current Collection is. It also makes it very quick to re-use work.

2. If we say only ChildCube1, it also creates a new workflow, where a Collection can act as a filter instead of just a starting point.

We have another rule #411 that says we don't recurse down into Datablocks that are in different scenes so we don't __always__ follow Blender's "children always count" philosophy when it would get confusing.

What do you think? I was partial to choice 1 for programmer-y reasons and the quick re-use potential.

**Comment by arb65912** [comment]
# 1 for me.

**Comment by tngreene** [comment]
Ben says (and is swaying me) the principle of least astonishment applies. Imagine a user's surprise that despite CollectionA being the only collection visible, some other piece of geometry is included from somewhere else.

I'm leaning towards #2.

@arb65912 , why do you vote 1 (and so passionately so!)

**Comment by arb65912** [comment]
Ted,  I think I just misunderstood the concept.....

I am very used to layers concept so I want all objects that are visible(selectable or marked somehow for export) to be exported, no other sub-objects from different collections.

Sorry for misunderstanding. :-)

**Comment by tngreene** [comment]
So far everyone is leaning towards option 2. See also #450 and #494 as collection of Exportable Collections is what this is all about

**Comment by dpospisil** [comment]
Agreed, please go for 2! That's also how it worked with layers...

I understand it's not standard procedure to report issues on random commits but I wanted to open a discussion about how should collection work before it's too late...

**Comment by dpospisil** [comment]
Just noticed #494. Ability to share parent-child anim structures across multiple exported objects is exactly the reason why I believe approach 2 is required...

**Comment by tngreene** [comment]
Closed: This case counts as an error. If anyone can think of a reason to have a child outside the collection please tell me. Otherwise, to me, it looks like a mistake or bad workflow. The parent-child relationship ha a strong meaning for us, to say "I have a child, but the child isn't part of the OBJ I'm in" seems very odd.

**Comment by dpospisil** [comment]
I don't get it. Why this should be error? The basic use case is when you need to share complex parent-child animation structures across multiple object. How would you model that?

**Comment by dpospisil** [comment]
Just an example how we used to work with 2.7:
Let's say you have an aircraft with complex animations. You need to export multiple object which contain the same animation structures. One object as a cockpit object (with manupulators) and other object with the actual mesh. How we do that, we put the animation empties in multiple layers, and the manipulators and meshes in separate layers, but all are children of the same animation empties.

How would yo do that in 2.8? We NEED to have the ability to have children from multiple collections to be parent of the same objects. The exporter should not absolutely treat that as error, just ignore object from other collections.

**Comment by dpospisil** [comment]
> Otherwise, to me, it looks like a mistake or bad workflow. The parent-child relationship ha a strong meaning for us, to say "I have a child, but the child isn't part of the OBJ I'm in" seems very odd.

So no, that's very essential workflow! Again, this worked very well in 2.7. You could have parent in layer X and children in layer Y. The exported did not stop just because of that, it just ignored children from layer Y.

I think that export by collections should work exactly how export by layers used to work.

**Comment by tngreene** [comment]
Good point! Thank you for your response and noticing the backwards compatibility issue!

**Comment by dpospisil** [comment]
Many thanks!
