### ISSUE TITLE
Latest for 2.79

### ISSUE THREAD

**Issue by rzimin** [X-Plane/XPlane2Blender#500]
Greetings, 

so with the recent release of Blender 2.8 and ongoing development of the exporter... can we have somewhere the latest usable version for 2.79?

Or we can grab the latest scripts and they would work with 2.79 as well as for 2.8?

Thank you,
Roman.

**Comment by airfightergr** [comment]
https://github.com/X-Plane/XPlane2Blender/releases/tag/v3.5.0-rc.1

**Comment by tngreene** [comment]
Thanks @airfightergr for the quick response! And glad to see @rzimin found it helpful enough to give a thumbs up. Congratulations on filing the 500th bug btw! I was wondering if it was going to be a feature request, bug report, or something else. Glad it was from the community instead of just more problems to solve!
