### ISSUE TITLE
Xplane..obj File Import doesn't appears on File-->Import Menu

### ISSUE THREAD

**Issue by mirkojovic** [X-Plane/XPlane2Blender#546]
Y recently installed on W10, blender 2.82 version and Last Beta1 of v4.0.0 xplane2blender add-on. 
Succesfully installed the add-on but I can't import any object because the menu doesn't give me this option. I used to use blender 2.78 and all worked perfectly.

**Comment by arb65912** [comment]
Despite historical name  XPlane2Blender does NOT have ability to import any XP objects.
You will need to use another program like ac3d.

**Comment by mirkojovic** [comment]
> 
> 
> Despite historical name XPlane2Blender does NOT have ability to import any XP objects.
> You will need to use another program like ac3d.

Why you insist in that? I used this script for export objects created with planemaker, with aircrafts of other versions and so on. I can understand that the new version of blender maked a lot of changes, but the script is being updated, slowly, but at least i can see activity in this repo. Don't forget that the new vulkan/metal implementation is taking a lot of time in the development team.

**Comment by tngreene** [comment]
Hi, I'm the developer of XPlane2Blender. @arb65912 insists that XPlane2Blender doesn't have an import feature because he is correct - it doesn't have an import feature. I will admit that the name and description in the addons panel is misleading, the description has been changed to not say anything about importing.

XPlane2Blender will not likely have an importer anytime soon, but if you absolutely had to you could use 2.49's importer, then use the converter in 2.79, then open it up in 2.80. Anything else isn't a priority.

**Comment by tngreene** [comment]
If you need any help with the exporter, please file more bugs and e-mail me. I love seeing what every one is working on and how to fix their problems, so thank you!
