### ISSUE TITLE
Blender Addon "uprade to2.8x required"

### ISSUE THREAD

**Issue by wildcardjed** [X-Plane/XPlane2Blender#555]
Blender preferences for xplane2blender add-on reports that "upgrade to 2.8x required".

The Blender version is currently 2.82a - seems to be an issue with xplane2blender detecting the version of Blender.

![image](https://user-images.githubusercontent.com/8616339/80523561-8ea8a600-898e-11ea-94b4-38200ba87198.png)

Thank you.

**Comment by airfightergr** [comment]
You have installed version 3.5 which is for blender 2.7x.

With 2.8x you must use version 4.0.0+
https://github.com/X-Plane/XPlane2Blender/releases/tag/v4.0.0-beta.1

**Comment by wildcardjed** [comment]
Thanks for responding @airfightergr .

I had the v4.0.0-beta.1 installed and was failing to get an X-Plane.obj file exported so thought I'd try the stable release version.

Perhaps I am doing something wrong in the export process - I'll get back to you.

Thanks for your input.

**Comment by tngreene** [comment]
@wildcardjed the top 3 things people don't do are
- don't give everything a material and (in Blender 2.80)
- Not make an exportable collection
- Make an exportable object inside an exportable collection

Check those next.

Thanks to @airfightergr for the quick response!

**Comment by wildcardjed** [comment]
Seems to have worked after I followed the error reports for XPlane2Blender log ;)

Thanks for your time.

**Comment by FenixDigitalB** [comment]
Instructions for installing blender2xplane says "download last NON-BETA versión" which is versión 3.5 so I installed that one.

I'm getting the same warning and you say for Blender 2.8x (only download available) we must use blender2xplane versión 4.00 which is BETA, which as a matter of fact contradicts your own words in installing instructions.

So... please clarify yourselves. I don't know what to do.

**Comment by tngreene** [comment]
Hi @FenixDigitalB,

I write instructions to be careful as possible, because I know many people use XPlane2Blender for production purposes. I only count release candidates as "so safe you could build payware with it, and if it breaks its totally my fault".

Despite v4.0.0 for Blender 2.80 being very very stable, its still not RC yet.

So, if you only want the most stable most tested most bug free possible experience, you'll have to use 2.79. If you're willing to put up with a few bugs and the (not really that big at this point) risk of using Blender 2.80 or higher, use v4.0.0.

https://github.com/X-Plane/XPlane2Blender/releases

Also it probably comes down to not changing the text in the README to be more clear, sorry. I'll do that now!
