### ISSUE TITLE
No File write

### ISSUE THREAD

**Issue by billhat** [X-Plane/XPlane2Blender#586]
Hi,
I use Blender V2.83.4 and XPlane2Blender V4.0.
All seem OK : On "Edit/preferences /Add-ons, I cant see "Import-Export X-Plane (.ogj).
I try to export a simple UV-Sphere just a few modifed.
No file create !
Is there à log file somewhere to know what append.
May be I dont use the rigth 3D model!
Thanks for help.
Regards
Bill

**Comment by billhat** [comment]
More information about my recent post.
I followed "Dan klaue's tutorial"on GitUb readme  and unfortunately, I do not pass the stage of exporting the simple cube !!! Nothing is exported. However, exporting to stl or other formats works fine.
Can you help me for this first stage? I don't see any error message.
Regards, Bill

**Comment by DWmFrancis** [comment]
Bill -

Unfortunately, Blender doesn’t always follow the drag-and-drop, point-and-click user interface conventions most of us learned using PCs and Macs. There are subtle visual hints, but sometimes they aren’t obvious enough to a new user. Order of operations is also very important. Here is how that appears for me;

1) Click on the cube. An orange outline will appear around the cube.

2) Click on the Exportable Object box. A white check mark with a blue background should appear in the box.

3) Click on the white triangle in the Exportable Object drop down menu box. Sub menus will appear for Name, Type, Textures, Levels of Detail, Advanced Options, Laminar Libraries, and Custom Properties.

Give the part a name.

Watch to make sure that the cube stays highlighted.

Click on the File menu header and drag down to Export and then X-Plane Object (.obj)

Next, you’ll select the location where the X-Plane object will be saved. It helps if that folder is inside your aircraft’s objects folder.

At the bottom of the Blender File View window is a text field you can use to meme the file. Try “cube.obj”

Finally, click on the blue Export x-Plane Object button. You may have to click on it twice.

A new file will appear in the folder with the name you used in the Exportable Object submenu earlier. Why the default name which Blender gave it isn’t automatically used is a mystery to me.

Give that a try and see if you can at least get a part to export.

**Comment by billhat** [comment]
Hi, 
thank's Francis,
I send you a mail with a little video to explain what "does not" append!
As you can see on the [picture....I'm not sure it's join!!!

![Blend2Xp-01](https://user-images.githubusercontent.com/20027264/90386563-09ecaf80-e085-11ea-86fe-e2f0867162fb.jpg)

There is nothing to the right of the file selection window.
With the "stl" export, I can  modify many parameters like scale ...

**Comment by billhat** [comment]
Rest of the story...
obviously, when I click on export, no file is created even I change the name.
On the top windows, in the working directory, you can see the stl file created just before.

**Comment by tngreene** [comment]
Hi, did you ever figure this out?

**Comment by billhat** [comment]
HI, sorry, I don't understand your remark, Have you read the topic  ?
Unfortunetly, I still haven't solved the problem

**Comment by tngreene** [comment]
XPlane2Blender makes an internal text file called `xplane2blender.log` when you export. Make one of the areas of the screen a text editor and open up that file. Here are some guesses as to what is going on

- You haven't specified a Root Collection (previously called Exportable Collection) or Root Object for the exporter to start at. Make a collection a root collection, add your cube to it, and then export or make some Empty datablock, make it a root object, make the cube a child of that empty, and then export
- Your cube doesn't have a material, so it won't export. It is giving you an error but you don't realize it
- You are exporting a file, but don't know the name or where to look. By default the root collection or object is used as the name and it would be saved in the same folder as the .blend file (or whatever folder you export to if using the File > Export method of exporting)

**Comment by tngreene** [comment]
A new intro to XPlane2Blender video has been made and put on vimeo. See the video here and download the test files in the link below the video.

https://developer.x-plane.com/tools/blender/

**Comment by DWmFrancis** [comment]
Ted -

I noticed that the video is still referring to pre-2.80 Blender and mentions layers.

Any plans to update the video so it is in sync with 4.0.0 and Blender 2.8/2.9?

Will this be posted on YouTube?

-df

**Comment by tngreene** [comment]
There is an unfortunate principle in software: The majority of users are people who have "figured it out" and are able to teach each other in a community and what they want is more features and less bugs. This new code is the highest value, Documentation and tutorials are always placed second - even though they are universally valuable and some new material feature may only be useful to a small group of people. This fact is painful for me - I sure wish I had had better docs to learn XPlane2Blender! Also more painful is the fact I don't have time to start up an officially guided documentation group, even though it would be useful! I know you personally have offered and I'm sorry I can't really take you up on the offer.

I have decided two things about increasing the quality of the documentation - to work on it a paragraphs a day instead of waiting for huge chunks of time that will never exist and turning e-mails and support into tutorials quicker. I can say the habit is already showing more promise and incremental progress is better than nothing.

Until then, I hope users will be able to work through inconsistencies on their own and form their own pools of knowledge on forums - though I have come to realize that moving from Blender 2.79 and Blender 2.80 not as obvious to some as it was to me. Very humbling and important.

Sorry to say that that is all that can be said or done at the moment on my end.

**Comment by arb65912** [comment]
Ted, your works has been absolutely outstanding through all the time I was using the exporter.

No need to feel sorry or apologize, one person can only do so much.
I have been also in the past asking for documentation but I totally agree that the exporter is a total priority which just shows with that latest great release.

Yes, thing can be sure figured out on our own and with help of others so you can concentrate on the core = code.

Since you will be writing documentation as time allows you I have one suggestion if it does not make things too complicated.

The existing documentation pieces are linked to certain releases of the exporter and it is kind of hard (for myself at least) to going between them and trying to find the right information.
Since the version 4 is released, maybe it would be possible to bring all the pieces of older documentation in one place related for that release?
I understand that things have been changing through the versions so maybe it is not an easy task to do but having the most important info in one place would sure benefit many.
Just a thought if not to hard to implement.

Thank you tons Ted for your outstanding work!!!!

I finally have my dream to come true happened, released version 4 on working with Blender 2.90.

Cheers, AJ

**Comment by billhat** [comment]
Hello, and thank you for your development and help, even though I haven't been able to make it work yet!
With the video, I thought that my problems would be solved unfortunately, as DWmFrancis pointed out, the video concerns the version of blender 2.80 and I already have a lot of difficulty to find the commands in blender, it does not facilitate the research of the solution.
I fully understand the difficulty of keeping the documentation up to date.

Question about tngreene's previous answer:

_XPlane2Blender makes an internal text file called xplane2blender.log when you export._
But I don't have any file created when exporting since absolutely nothing happens! nothing is exported.

I added a material although I don't understand why this is necessary since it only affects the appearance of the surfaces and not their physical reality. but....OK it's done and always no files creates

_You haven't specified a Root Collection_
Which root? root  of blender instal on C: ? or the root where is the ".blen" file, which is already the case as you cant see on my screenshoot.

Thank you for your help

**Comment by arb65912** [comment]
Bill,

Take a look at attached screenshots. This is what Ted meant by Root Collection.

The  xplane2blender.log file will be created in the same directory where is your Blender file.

![Root Collection](https://user-images.githubusercontent.com/16321070/92996870-e29ace00-f4dc-11ea-91bc-5513a8e4e549.jpg)

![Root Collection 2](https://user-images.githubusercontent.com/16321070/92996878-ec243600-f4dc-11ea-9fda-3f107ce3df23.jpg)

**Comment by tngreene** [comment]
Hi @billhat, you make a good point about roots. There is really no good name for them that can't be confused with a Blender thing, OS thing, or further more difficult Computer Science thing. Oh well.

Are you working successfully yet? Great screenshots @arb65912 ! Thanks

**Comment by tngreene** [comment]
[simple_cube.zip](https://github.com/X-Plane/XPlane2Blender/files/5248047/simple_cube.zip)


This is a simple cube that moves from one place to another. If this doesn't export just by pressing the export button then there's something else wrong. Try it out.

**Comment by tngreene** [comment]
As there hasn't been a response, I'm closing this for now. Feel free to make new comments or bugs and we'll continue the discussion.
