### ISSUE TITLE
Support for Blender 3

### ISSUE THREAD

**Issue by rccDave** [X-Plane/XPlane2Blender#684]
I realize it is an overhaul and Blender is rapidly developing, but it would sure be great if XPlane2Blender was geared for the latest version of Blender and not one now getting quite old.

**Comment by kbrandwijk** [comment]
Blender 3.0 is a month old, 2.9x is definitely not 'getting quite old', as a matter of fact, 2.93 is an LTS release with support until 2023. Not that it wouldn't be great to work towards 3.x compatibility, but your perspective is a bit skewed.

**Comment by lehthanis** [comment]
I'd be interested to know how much effort is required to make the mods
needed for 3 compatibility... Not full functionality, just compatibility.
Because us Linux users on rolling distributions get blender updates as
they're made with our system updates. It's a pain to have to then side load
older versions.

**Comment by arb65912** [comment]
I would be interested when we will have Released version of the exporter before we have compatibility with 3.x and importer

**Comment by rccDave** [comment]
> kbrandwijk wrote: "Blender 3.0 is a month old, 2.9x is definitely not 'getting quite old', as a matter of fact, 2.93 is an LTS release..."

Fair point, but the documentation says "This addon is for 2.80" (not 2.9).  It mentions "2.9 seems to work", but that's not really the same as saying "2.93 is fully supported".  So, you are right, XPlane2Blender should be developed for the latest LTS.  That should reduce the chasing of revs.

(Wonder when the name will reflect what the plugin does: Blender2XPlane.)

**Comment by kbrandwijk** [comment]
> Fair point, but the documentation says "This addon is for 2.80" (not 2.9). It mentions "2.9 seems to work", but that's not really the same as saying "2.93 is fully supported". So, you are right, XPlane2Blender should be developed for the latest LTS. That should reduce the chasing of revs.

Okay, you got me there ;) It's been a while since I was active on this project, I was under the impression that an intermittent release since then added official 2.9x support, but I guess not. Pointing to 2.8x, it _is_ fair to say that version is getting pretty old. I think we're on the same page here, try to keep up with LTS releases (2.93 LTS), and keep an eye on quick wins to stretch that support to latest (in this case 3.x).

**Comment by JT8D-17** [comment]
I'm using 4.2.0-alpha1 in Blender 3.0 and the model I'm working on exports in usable form.

**Comment by rccDave** [comment]
That's a good sign.

**Comment by haibaadel** [comment]
If it is at least supported for 2.93, it'll be good, as many good things included in 2.93, hopefully will see it soon.

**Comment by lehthanis** [comment]
I have discovered through testing that XPlane2Blender works without issue for Blender 3.0.1...however...there is a problem with Python 3.10.2.  I will be raising another issue to get that fixed...it's very simple.  If you're getting an error activating the addon related to importing Iterable, pay attention to the issue I post in a few minutes.

**Comment by bsupnik** [comment]
@lehthanis if the only issue is collection python errors, I think 4.2.0 is fine - as far as I know people are using it. If there is a python-version-specific bug, please file an issue listing the specific local machine config that hoses things. I think most users get their python from Blender, os a version should just wrok.
