### ISSUE TITLE
4.0.0 alpha 6

### ISSUE THREAD

**Issue by Swiss003** [X-Plane/XPlane2Blender#690]
at first it went very well with the export but now when I export it rotates the object in once does anyone know how to fix this?

**Comment by DWmFrancis** [comment]
This may be a silly question in reply, but; Did you do *apply* any rotations before saving and exporting?

**Comment by Swiss003** [comment]
Op di 1 feb. 2022 om 12:48 schreef DWmFrancis ***@***.***>

**Comment by DWmFrancis** [comment]
Did you apply the rotation before exporting?
<img width="793" alt="Screen Shot 2022-02-01 at 1 04 14 PM" src="https://user-images.githubusercontent.com/7341970/152043257-94721eac-541f-4111-8793-6ad77cee31a6.png">

**Comment by Swiss003** [comment]
No, I didn't.

Op di 1 feb. 2022 om 21:08 schreef DWmFrancis ***@***.***>

**Comment by DWmFrancis** [comment]
You have to “apply” the transformations before exporting. That can be a little confusing, since it’s natural to expect that what you are seeing on the display is what will be in the exported file, but Blender isn’t always intuitively obvious.

Any geometry changes (“transformations”) you do to an object need to be (“applied”) before you export them.

-df

http://thinkingofdesign.blogspot.com
